ArcheryComp/ArcheryComp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.template.loader import render_to_string
from django.http import HttpResponse
from . import views

urlpatterns = [
    path('admin/',          admin.site.urls),
    path('',                views.IndexView.as_view(), name='home_page'),
    path('competitions/',   include('competitions.urls',   namespace='competitions')),
    path('participations/', include('participations.urls', namespace='participations')),
    path('users/',          include(('users.urls', 'users'), namespace='users')),
]

ArcheryComp/users/urls.py
from django.urls import path, include
from . import views
from . import forms

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/',  views.ProfileUpdateView.as_view(), name='profile'),
    path('profile/<str:username>/',  views.ProfileDetailView.as_view(), name='profile_view'),
    path('profile/<int:sportsmen_id>/',  views.ProfileDetailView.as_view(), name='profile_view_by_id'),
    path('login/',    views.MyLoginView.as_view(),  name='login'),
    path('', include('django.contrib.auth.urls')),
]

ArcheryComp/users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    SEX_CHOICES = [
        ('M', 'Мужчины/Юноши'),
        ('F', 'Женщины/Девушки')
    ]

    RANK_CHOICES = [
        ('3-й юношеский', '3-й юношеский'),
        ('2-й юношеский', '2-й юношеский'),
        ('1-й юношеский', '1-й юношеский'),
        ('3-й спортивный', '3-й спортивный'),
        ('2-й спортивный', '2-й спортивный'),
        ('1-й спортивный', '1-й спортивный'),
        ('КМС', 'КМС'),
        ('МС', 'МС'),
        ('МСМК', 'МСМК'),
        ('Организатор', 'Организатор'),
        ('Нет разряда', 'Нет разряда'),
    ]

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile'
    )

    second_name = models.CharField(
        max_length=50,
        null=True,
        blank=True
    )

    sex = models.CharField(
        max_length=10,
        choices=SEX_CHOICES,
        default='M',
    )
    
    date_of_birth = models.DateField(null=True, blank=True)

    rank = models.CharField(
        max_length=20,
        choices=RANK_CHOICES,
        default='-',
        null=True,
        blank=True
    )
    region = models.CharField(max_length=250, null=True, blank=True)

    organization = models.CharField(
        max_length=250,
        null=True,
        blank=True,
    )
    
    coach = models.CharField(
        max_length=150,
        null=True,
        blank=True
    )

    def __str__(self):
        return f'{self.user.username} Profile'

    

ArcheryComp/users/forms.py
from typing import Any
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Profile

User = get_user_model()


class UserCreationForm(UserCreationForm):
    
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Имя пользователя',
                                      'class':       'auth-forms-label'})
    )

    email = forms.EmailField(
        label=_('Email'),
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email',
                                       'placeholder' : 'Email',
                                       'class':        'auth-forms-label'})
    )
    
    password1 = forms.CharField(
        label=_('Password'),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password',
                                          'placeholder' : 'Пароль',
                                          'class':        'auth-forms-label'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_('Password confirmation'),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password',
                                          'placeholder' : 'Подтвердите пароль',
                                          'class':        'auth-forms-label'}),
        strip=False,
        help_text=_('Подтвердите пароль для верификации.'),
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email')


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {'username':'Имя пользователя',
                  'email':'Email',
                  'first_name':'Имя',
                  'last_name':'Фамилия'}
        


class ProfileUpdateForm(forms.ModelForm):
    
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'placeholder':'ГГГГ-ММ-ДД'}),
                                    required=False)
    date_of_birth.default_error_messages = {
        "invalid": _("Введите дату в форме: ГГГГ-ММ-ДД"),
    } 

    class Meta:
        model = Profile
        fields = ['second_name','sex',
                  'date_of_birth', 'rank',
                  'region','organization',
                  'coach']
        labels = {'second_name':'Отчество',
                  'sex':'Пол',
                  'date_of_birth':'Дата рождения', 
                  'rank':'Звание',
                  'region':'Регион',
                  'organization':'Организация',
                  'coach':'Тренер'}
        
        error_messages = {  #'second_name':'',
        #                     'sex':'',
                            'date_of_birth': {'invalid':_('Форма даты: ГГГГ-ММ-ДД'),
                                              'invalid_date':_('Форма даты: ГГГГ-ММ-ДД')}, 
                            # 'rank':'',
                            # 'region':'',
                            # 'organization':'',
                            # 'coach':''
                         }
        

class UserLoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(
                                attrs={'autofocus': True,
                                       'placeholder': 'Имя пользователя',
                                       'class':       'auth-forms-label'}))
    password = forms.CharField(
        label=_('Password'),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password',
                                          'placeholder': 'Пароль',
                                          'class':       'auth-forms-label'}),
    )

    

ArcheryComp/users/views.py
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView
from django.shortcuts import render, redirect
from .forms import UserUpdateForm, ProfileUpdateForm, UserCreationForm, UserLoginForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User


class RegisterView(View):
    template_name = 'registration/register.html'
    
    def get(self, request):
        context = {
            'form': UserCreationForm()
        }
        print('in register "get" method')
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('users:profile')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)
    
class ProfileDetailView(View):
    def get(sels, request, username, *args, **kwargs):
        user = User.objects.get(username=username)
        return render(request, 'users/profile_detail.html', {"user_": user})
 
class ProfileUpdateView(LoginRequiredMixin, View):

    def get(self, request):
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        
        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }
        
        return render(request, 'users/profile_update.html', context)
    
    def post(self,request):
        user_form = UserUpdateForm(
            request.POST, 
            instance=request.user
        )
        profile_form = ProfileUpdateForm(
            request.POST,
            request.FILES,
            instance=request.user.profile
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            
            # messages.success(request,'Your profile has been updated successfully')
            
            return redirect(reverse('users:profile_view', kwargs={'username':request.user.username}))
        else:
            context = {
                'user_form': user_form,
                'profile_form': profile_form
            }
            # messages.error(request,'Error updating you profile')
            
            return render(request, 'users/profile_update.html', context)
        
class MyLoginView(LoginView):
    form_class = UserLoginForm
    template_name = 'registration/login.html'
    
    
    

ArcheryComp/users/templates/users/profile.html
{% extends 'ArcheryComp/base.html' %} 

{% block title %}
ArcheryComp Profile
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Личный кабинет</h1>  
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<div class="container">
    <h3>Пользователь: {{ user.username }}</h3>
    <form method="post">
        {% csrf_token %}

        {% for field in user_form %}
            <div class="row mx-1 mt-2">
                <div class="col-xl-4 col-md-6 col-sm-12">
                    <div class="row">{{ field.label_tag }}</div>
                    <div class="row">{{field}}</div>
                </div>
            </div>
        {% endfor %}
        {% for field in profile_form %}
            <div class="row mx-1 mt-2">
                <div class="col-xl-4 col-md-6 col-sm-12">
                    <div class="row">{{ field.label_tag }}</div>
                    <div class="row">{{field}}</div>
                </div>
            </div>
        {% endfor %}

    
        <div class="row mx-1 mt-4 mb-5">
            <div class="col-xl-4 col-md-7 col-sm-12">
                <div class="row">
                    <button type="submit" class="confirm-btn">Сохранить</button>
                </div>
            </div>
        </div>
        
    </form>
    
</div>



{% endblock content %}

ArcheryComp/users/templates/users/profile_detail.html
{% extends 'ArcheryComp/base.html' %} 

{% block title %}
ArcheryComp Profile
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Личный кабинет</h1>  
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<div class="container">
    <div class="row mt-2">
        <h3>Пользователь: {{ user_.username }}</h3>
    </div>
    <div class="row">
        <div class="row justify-content-start mx-1 mt-2">
            <div class="col-xl-4 col-md-7 col-sm-12">
                ФИО: {{ user_.last_name }} {{ user_.first_name }} {{ user_.profile.second_name }}
            </div>
        </div>
        <div class="row justify-content-start mx-1 mt-2">
            <div class="col-xl-4 col-md-7 col-sm-12">
                Уровень: {{ user_.profile.rank }}
            </div>
        </div>
    </div>
    
    <!--username - id спорстмена ... -->
    <div class="row mx-1 mt-2">
        <div class="col-xl-4 col-md-7 col-sm-12">
            <a href="{% url 'participations:profile' user_.username %}" class="confirm-btn">Участия пользователя</a>
        </div>
    </div>
    {% if user.is_authenticated and user == user_ %}
    <div class="row mx-1 mt-2">
        <div class="col-xl-4 col-md-7 col-sm-12">
            <a href="{% url 'users:profile' %}" class="confirm-btn">Редактировать профиль</a>
        </div>
    </div>
    {% endif %}
    
    
</div>



{% endblock content %}

ArcheryComp/users/templates/users/profile_update.html
{% extends 'ArcheryComp/base.html' %} 

{% block title %}
ArcheryComp Profile
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Личный кабинет</h1>  
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<div class="container">
    <h3>Пользователь: {{ user.username }}</h3>
    <form method="post">
        {% csrf_token %}

        {% for field in user_form %}
            <div class="row mx-1 mt-2">
                <div class="col-xl-4 col-md-6 col-sm-12">
                    <div class="row">{{ field.label }}</div>
                    <div class="row">{{ field }}</div>
                    {% for error in field.errors%}
                    <div class="row">{{ error }}</div>
                    {% endfor %}
                    
                </div>
            </div>
        {% endfor %}
        {% for field in profile_form %}
            <div class="row mx-1 mt-2">
                <div class="col-xl-4 col-md-6 col-sm-12">
                    <div class="row">{{ field.label_tag }}</div>
                    <div class="row">{{field}}</div>
                    {% for error in field.errors%}
                    <div class="row">{{ error }}</div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}

    
        <div class="row mx-1 mt-4 mb-5">
            <div class="col-xl-4 col-md-7 col-sm-12">
                <div class="row">
                    <div class="col-6">
                        <button type="submit" class="confirm-btn btn-w-100">Сохранить</button>
                    </div>
                    <div class="col-6">
                        <a href="{% url 'users:profile_view' user.username %}" class="confirm-btn">Отменить</a>
                    </div>
                </div>
                
            </div>
        </div>
        
    </form>
    
    
</div>



{% endblock content %}