ArcheryComp/ArcheryComp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.template.loader import render_to_string
from django.http import HttpResponse
from . import views

urlpatterns = [
    path('admin/',          admin.site.urls),
    path('',                views.IndexView.as_view(), name='home_page'),
    path('competitions/',   include('competitions.urls',   namespace='competitions')),
    path('participations/', include('participations.urls', namespace='participations')),
    path('users/',          include(('users.urls', 'users'), namespace='users')),
]

ArcheryComp/competitions/urls.py
from django.urls import path, include
from competitions import views
from participations import views as views_p

app_name = 'competitions'

urlpatterns = [
    path('',              views.IndexView.as_view(),            name='index'),
    path('classical/',    views.ClassicalListView.as_view(),    name='classical_list'),
    path('compound/',     views.CompoundListView.as_view(),     name='compound_list'),
    path('3D/',           views.DListView.as_view(),            name='D_list'),
    path('acheri/',       views.AcheriListView.as_view(),       name='acheri_list'),
    path('asymmetrical/', views.AsymmetricalListView.as_view(), name='asymmetrical_list'),
    path('competition_detail/<int:comp_id>/', include([
        path('', views.CompetitionDetailView.as_view(), name='competition_detail'),
        path('/<int:program_id>/', include([
            path('add_personal/', views_p.PersonalParticipationCreateView.as_view(), name='add_personal'),
            path('add_team/',     views_p.TeamParticipationCreateView.as_view(),     name='add_team'),
            path('add_mixed/',    views_p.MixedParticipationCreateView.as_view(),    name='add_mixed'),
            ])),
        path('/<int:participation_id>/', include([
            path('update_personal/', views_p.PersonalParticipationUpdateView.as_view(), name='update_personal'),
            path('update_team/',     views_p.TeamParticipationUpdateView.as_view(),     name='update_team'),
            path('update_mixed/',    views_p.MixedParticipationUpdateView.as_view(),    name='update_mixed'),
        ])),
        path('add_program/', views.IndexView.as_view(), name='add_program'),
        path('delete/', views.ClassicalDeleteView.as_view(), name='delete_classical_comp')
    ])),
]

ArcheryComp/users/urls.py
from django.urls import path, include
from . import views
from . import forms

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/',  views.ProfileUpdateView.as_view(), name='profile'),
    path('profile/<str:username>/',  views.ProfileDetailView.as_view(), name='profile_view'),
    path('profile/<int:sportsmen_id>/',  views.ProfileDetailView.as_view(), name='profile_view_by_id'),
    path('login/',    views.MyLoginView.as_view(),  name='login'),
    path('', include('django.contrib.auth.urls')),
]

ArcheryComp/competitions/models.py
from django.db import models
from django.contrib.auth.models import User

class Competition(models.Model):
    DISCIPLINE_CHOICES = [
        ('Classical', 'Классический лук'),
        ('Compound', 'Блочный лук'),
        ('3D', '3Д стрельба из лука'),
        ('Acheri', 'Ачери'),
        ('Asymmetrical', 'Ассиметричный лук')
    ]
    DISCIPLINE_CHOICES_DICT = {k[0]:k[1] for k in DISCIPLINE_CHOICES}
    STATUS_CHOICES = [
        ('Championship', 'Чемпионат России'),
        ('Cup', 'Кубок России'),
        ('Pervenstvo', 'Первенство России'),
        ('Vseros', 'Всероссийские соревнования')
    ]

    comp_id = models.IntegerField(primary_key=True)
    title = models.CharField(
        max_length=250
    )
    description = models.TextField()
    discipline = models.CharField(
        max_length=50,
        choices=DISCIPLINE_CHOICES,
        default='Classical',
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
    )
    started_at = models.DateField()
    finished_at = models.DateField()
    location = models.CharField(max_length=250)

    organizer = models.ForeignKey(
        User,
        related_name='competitions',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.title

class Program(models.Model):
    DISTANCE_CHOICES = [
        (12, '12'),
        (18, '18'),
        (28, '28'),
        (30, '30'),
        (40, '40'),
        (45, '45'),
        (50, '50'),
        (60, '60'),
        (70, '70'),
        (90, '90'),
    ]
    TEAM_CHOICES = [
        ('Personal', 'Личные соревнования'),
        ('Teams', 'Командные соревнованиия'),
        ('Mixed', 'Смешанные командные соревнования')
    ]
    SEX_CHOICES = [
        ('M', 'Мужчины/Юноши'),
        ('F', 'Женщины/Девушки')
    ]

    name = models.CharField(
        max_length=100,
        unique=True,
    )
    distance_1 = models.PositiveSmallIntegerField(choices=DISTANCE_CHOICES)
    distance_2 = models.PositiveSmallIntegerField(choices=DISTANCE_CHOICES)
    shots = models.PositiveSmallIntegerField()
    finals = models.PositiveSmallIntegerField(
        choices=DISTANCE_CHOICES,
        null=True,
        blank=True,
    )
    team = models.CharField(
        max_length=10,
        choices=TEAM_CHOICES
    )
    sex = models.CharField(
        max_length=10,
        choices=SEX_CHOICES,
        null=True,
        blank=True,
    )
    age_limit = models.SmallIntegerField(
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

ArcheryComp/participations/models.py
from django.db import models
from django.contrib.auth.models import User
from competitions.models import Competition, Program
from users.models import Profile
from django.contrib.auth.models import User

class PersonalParticipation(models.Model):
    competition = models.ForeignKey(
        Competition,
        related_name='participations',
        on_delete=models.CASCADE
    )
    program = models.ForeignKey(
        Program,
        related_name='participations',
        on_delete=models.RESTRICT
    )
    sportsman = models.ForeignKey(
        User,
        related_name='participations',
        on_delete=models.CASCADE
    )
    place = models.PositiveSmallIntegerField()
    place_qualification = models.PositiveSmallIntegerField()
    sum_qualification = models.PositiveSmallIntegerField()

    def __str__(self):
        return f'{self.sportsman}, {self.competition}'


class TeamParticipation(models.Model):
    competition = models.ForeignKey(
        Competition,
        related_name='team_participations',
        on_delete=models.CASCADE
    )
    program = models.ForeignKey(
        Program,
        related_name='team_participations',
        on_delete=models.RESTRICT
    )
    sportsman_1 = models.ForeignKey(
        User,
        related_name='team_participations_1',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    sportsman_2 = models.ForeignKey(
        User,
        related_name='team_participations_2',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    sportsman_3 = models.ForeignKey(
        User,
        related_name='team_participations_3',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    place = models.PositiveSmallIntegerField()
    place_qualification = models.PositiveSmallIntegerField()
    sum_qualification = models.PositiveSmallIntegerField()

    def __str__(self):
        return f'({self.sportsman_1}, {self.sportsman_2}, {self.sportsman_3}) {self.competition}'

class MixedParticipation(models.Model):
    competition = models.ForeignKey(
        Competition,
        related_name='mixed_participations',
        on_delete=models.CASCADE
    )
    program = models.ForeignKey(
        Program,
        related_name='mixed_participations',
        on_delete=models.RESTRICT
    )
    sportsman_M = models.ForeignKey(
        User,
        related_name='mixed_participations_M',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    sportsman_F = models.ForeignKey(
        User,
        related_name='mixed_participations_F',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    place = models.PositiveSmallIntegerField()
    place_qualification = models.PositiveSmallIntegerField()
    sum_qualification = models.PositiveSmallIntegerField()

    def __str__(self):
        return f'({self.sportsman_M}, {self.sportsman_F}) {self.competition}'

ArcheryComp/competitions/forms.py
from typing import Any, Mapping
from django.core.files.base import File
from django.db.models.base import Model
from django.forms import ModelForm
from django.forms.utils import ErrorList
from .models import Program
from django import forms


class ProgramForm(ModelForm):
    class Meta:
        model = Program
        fields = ['name']
        labels = {'name':'Наименование'}

ArcheryComp/competitions/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.edit import UpdateView, DeleteView
from django.http import HttpResponse
from django.urls import reverse
from .models import Competition


class IndexView(View):
    template_name = 'competitions/index.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


from django.views.generic import ListView


class DisciplineListView(ListView):
    model = Competition
    template_name = 'competitions/discipline.html'
    discipline = ''

    def get_queryset(self):
        return Competition.objects.filter(discipline=self.discipline)

    def get(self, request, *args, **kwargs):
        competitions = self.get_queryset().order_by('started_at')

        return render(request, self.template_name, context={'competitions': competitions,
                                                            'discipline': self.model.DISCIPLINE_CHOICES_DICT[
                                                                self.discipline],
                                                            })


class ClassicalListView(DisciplineListView):
    discipline = 'Classical'


class CompoundListView(DisciplineListView):
    discipline = 'Compound'


class DListView(DisciplineListView):
    discipline = '3D'


class AcheriListView(DisciplineListView):
    discipline = 'Acheri'


class AsymmetricalListView(DisciplineListView):
    discipline = 'Asymmetrical'


from django.views.generic import DetailView


class CompetitionDetailView(DetailView):
    model = Competition
    template_name = 'competitions/competition_detail.html'
    pk_url_kwarg = 'comp_id'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        competition = self.object
        personal_participations = competition.participations.all()
        team_participations = competition.team_participations.all()
        mixed_participations = competition.mixed_participations.all()
        participations_type = [personal_participations, team_participations, mixed_participations]
        programs = set()

        for participations in participations_type:
            for participation in participations:
                programs.add(participation.program)

        for program in programs:
            program.personal_program = []
            program.team_program = []
            program.mixed_program = []

            if program.team == 'Personal':
                participations = competition.participations.filter(program=program)
                for participation in participations:
                    program.personal_program.append([participation.sportsman,
                                                     participation.place,
                                                     participation.place_qualification,
                                                     participation.sum_qualification,
                                                     participation.id])
                program.personal_program.sort(key=lambda x: x[1])
            elif program.team == 'Teams':
                participations = competition.team_participations.filter(program=program)

                for participation in participations:
                    program.team_program.append([(participation.sportsman_1,
                                                  participation.sportsman_2,
                                                  participation.sportsman_3),
                                                 participation.place,
                                                 participation.place_qualification,
                                                 participation.sum_qualification,
                                                 participation.id])

                program.team_program.sort(key=lambda x: x[1])


            else:
                participations = competition.mixed_participations.filter(program=program)
                for participation in participations:
                    program.mixed_program.append([(participation.sportsman_M,
                                                   participation.sportsman_F),
                                                  participation.place,
                                                  participation.place_qualification,
                                                  participation.sum_qualification,
                                                  participation.id])
                program.mixed_program.sort(key=lambda x: x[1])

        return render(request, self.template_name, context={'competition': competition,
                                                            'programs': programs,
                                                            'discipline': competition.DISCIPLINE_CHOICES_DICT[
                                                                competition.discipline]})


class ClassicalDeleteView(DeleteView):
    model = Competition
    pk_url_kwarg = 'comp_id'
    success_url = reverse_lazy('competitions:classical_list')
    template_name = 'competitions/delete_classical_comp.html'

ArcheryComp/competitions/templates/competitions/competition_detail.html
{% extends 'competitions/competitions_base.html' %}

{% block title %}
ArcheryComp Соревнования
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1> {{discipline}} - {{ competition.title }} </h1>
        </div>
    </div>
</div>
{% endblock %}

{% block main %}

<div class="container">
    <div class="row mt-2 mb-4">
        {{ competition.description }}
    </div>
    <div class="row comp-types">
        <div class="col text-center comp-type p-1 m-1">
            <a href="{% url 'competitions:delete_classical_comp' competition.comp_id %}"onclick="return confirm('Вы уверены, что хотите удалить это соревнование?');">Удалить соревнование</a>
        </div>
    </div>
    <div class="row">
        {% for program in programs %}
            <div class="row">
                <div class="row ">
                    <h3> {{ program.name }}

                        {% if perms.competitions.change_program %}
                        <a href="#" class=""><i class="icon-cog"></i></a>
                        {% endif %}

                    </h3>
                </div>
                <div class="row mb-5">

                    {% if program.team == 'Personal' %}
                        <div class="row">
                            <div class="col">Спортсмен</div>
                            <div class="col">Место</div>
                            <div class="col">Место в квалификации</div>
                            <div class="col">Сумма в квалификации</div>
                            <div class="col-1"></div>
                        </div>
                        <div class="line" style="background-color: black;"></div>

                        {% for sportsmen, place, place_qualification, sum_qualification, participation_id  in program.personal_program  %}
                        <div class="row">
                            <div class="col">
                                <a href="#" class="">{{ sportsmen }}</a>
                            </div>
                            <div class="col">{{ place }}</div>
                            <div class="col">{{ place_qualification }}</div>
                            <div class="col">{{ sum_qualification }}</div>

                            {% if perms.paticipations.change_personalparticipation %}
                            <div class="col-1" style="width: fit-content;">
                                <a href="{% url 'competitions:update_personal' competition.comp_id participation_id %}">
                                    <i class="icon-cog"></i>
                                </a>
                            </div>
                            {% endif %}
                            <div class="line"></div>
                        </div>
                        {% endfor %}

                        {% if perms.paticipations.add_personalparticipation %}
                        <div class="row">
                            <a href="{% url 'competitions:add_personal' competition.comp_id program.id %}">
                                <i class="icon-plus"></i>
                            </a>
                        </div>
                        {% endif %}

                    {% elif program.team == 'Teams' %}
                        <div class="row">
                            <div class="col">Команда</div>
                            <div class="col">Место</div>
                            <div class="col">Место в квалификации</div>
                            <div class="col">Сумма в квалификации</div>
                            <div class="col-1"></div>
                        </div>
                        <div class="line" style="background-color: black;"></div>

                        {% for sportsmens, place, place_qualification, sum_qualification, participation_id in program.team_program  %}
                        <div class="row">
                            <div class="col">
                                {% for sportsmen in sportsmens %}
                                    <div class="row">
                                        <a href="#" class="">{{ sportsmen }}</a>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col">{{ place }}</div>
                            <div class="col">{{ place_qualification }}</div>
                            <div class="col">{{ sum_qualification }}</div>

                            {% if perms.paticipations.change_teamparticipation %}
                            <div class="col-1" style="width: fit-content;">
                                <a href="{% url 'competitions:update_personal' competition.comp_id participation_id %}">
                                    <i class="icon-cog"></i>
                                </a>
                            </div>
                            {% endif %}
                            <div class="line"></div>
                        </div>
                        {% endfor %}

                        {% if perms.paticipations.add_teamparticipation %}
                        <div class="row">
                            <a href="{% url 'competitions:add_team' competition.comp_id program.id %}" class="">
                                <i class="icon-plus"></i>
                            </a>
                        </div>
                        {% endif %}




                    {% else %}
                        <div class="row">
                            <div class="col">Команда</div>
                            <div class="col">Место</div>
                            <div class="col">Место в квалификации</div>
                            <div class="col">Сумма в квалификации</div>
                            <div class="col-1"></div>
                        </div>
                        <div class="line" style="background-color: black;"></div>

                        {% for sportsmens, place,place_qualification, sum_qualification, participation_id in program.mixed_program  %}
                        <div class="row">
                            <div class="col">
                                {% for sportsmen in sportsmens %}
                                    <div class="row">
                                        <a href="#" class="">{{ sportsmen }}</a>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col">{{ place }}</div>
                            <div class="col">{{ place_qualification }}</div>
                            <div class="col">{{ sum_qualification }}</div>

                            {% if perms.paticipations.change_mixedparticipation %}
                            <div class="col-1" style="width: fit-content;">
                                <a href="{% url 'competitions:update_personal' competition.comp_id participation_id %}">
                                    <i class="icon-cog"></i>
                                </a>
                            </div>
                            {% endif %}
                            <div class="line"></div>
                        </div>
                        {% endfor %}

                        {% if perms.paticipations.add_mixedparticipation %}
                        <div class="row">
                            <a href="{% url 'competitions:add_mixed' competition.comp_id program.id %}" class="">
                                <i class="icon-plus"></i>
                            </a>
                        </div>
                        {% endif %}

                    {% endif %}

                </div>
            </div>
        {% endfor %}

        {% if perms.paticipations.add_mixedparticipation %}
        <div class="row mb-5">
            <a href="{% url 'competitions:add_program' competition.comp_id %}" style="text-decoration: none;">
                <i class="icon-plus">Добавить программу испытаний</i>
            </a>
        </div>
        {% endif %}
    </div>
</div>


{% endblock %}

ArcheryComp/competitions/templates/competitions/competitions.html
{% extends 'ArcheryComp/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col competition-list">
            {% block main %}{% endblock %}
        </div>

        <div class="col-3 " >
            <div class="row justify-content-end" >
                <div class="col-12" >
            <!-- <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse flex-row" id="navbarNav"> -->
                        <ul class="row navbar-nav text-center" style="position: fixed;">
                            <li class="nav-item mt-2">
                                <a href="{% url 'competitions:classical_list' %}" class="nav-link comp-sidebar-elem">Классический лук</a>
                            </li>
                            <li class="nav-item mt-2">
                                <a href="{% url 'competitions:compound_list' %}" class="nav-link comp-sidebar-elem">Блочный лук</a>
                            </li>
                            <li class="nav-item mt-2">
                                <a href="{% url 'competitions:D_list' %}" class="nav-link comp-sidebar-elem">3Д стрельба из лука</a>
                            </li>
                            <li class="nav-item mt-2">
                                <a href="{% url 'competitions:acheri_list' %}" class="nav-link comp-sidebar-elem">Ачери</a>
                            </li>
                            <li class="nav-item mt-2">
                                <a href="{% url 'competitions:asymmetrical_list' %}" class="nav-link comp-sidebar-elem">Ассиметричный лук</a>
                            </li>
                        </ul>
                    <!-- </div>
                </div>
            </nav>     -->
        </div>
        </div>
        </div>
    </div>
</div>

{% endblock %}

ArcheryComp/competitions/templates/competitions/competitions_base.html
{% extends 'ArcheryComp/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col competition-list">
            {% block main %}{% endblock %}
        </div>

        <div class="col-2 " >
            <div class="row justify-content-end" >
                <div class="col-12" >
            <!-- <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse flex-row" id="navbarNav"> -->
                        <ul class="row navbar-nav text-center disciplines-navbar">
                            <li class="nav-item mt-2">
                                <a href="{% url 'competitions:classical_list' %}" class="nav-link comp-sidebar-elem">Классический лук</a>
                            </li>
                            <li class="nav-item mt-2">
                                <a href="{% url 'competitions:compound_list' %}" class="nav-link comp-sidebar-elem">Блочный лук</a>
                            </li>
                            <li class="nav-item mt-2">
                                <a href="{% url 'competitions:D_list' %}" class="nav-link comp-sidebar-elem">3Д стрельба из лука</a>
                            </li>
                            <li class="nav-item mt-2">
                                <a href="{% url 'competitions:acheri_list' %}" class="nav-link comp-sidebar-elem">Ачери</a>
                            </li>
                            <li class="nav-item mt-2">
                                <a href="{% url 'competitions:asymmetrical_list' %}" class="nav-link comp-sidebar-elem">Ассиметричный лук</a>
                            </li>
                        </ul>
                    <!-- </div>
                </div>
            </nav>     -->
        </div>
        </div>
        </div>
    </div>
</div>

{% endblock %}

ArcheryComp/competitions/templates/competitions/delete_classical_comp.html
{% extends 'competitions/competitions_base.html' %}

{% block content %}
    <h1>Удаление соревнования</h1>
    <p>Вы уверены, что хотите удалить соревнование "{{ competition.title }}"?</p>

    <form action="{% url 'competitions:delete_classical_comp' competition.comp_id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'competitions:competition_detail' competition.comp_id %}">Отмена</a>
    </form>
{% endblock %}

ArcheryComp/competitions/templates/competitions/discipline.html
{% extends 'competitions/competitions_base.html' %}

{% block title %}
ArcheryComp Соревнования
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Список соревнований - {{ discipline }}</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block main %}

<div class="container">
    
    {% if competitions|length == 0 %}
    <div class="row comp-list mt-2">Соревнований нет</div>
    {% else %}

        {% for competition in competitions %}
            <div class="row mt-2 comp-list">
                
                <div class="col">
                    <a href="{% url 'competitions:competition_detail' competition.comp_id %}"
                class="comp-list-hover">{{ competition.title }}</a>
                </div>
                
                <!-- Edit competition -->
                {% if perms.competitions.change_competition %}
                <div class="col">
                    <div class="row justify-content-start">
                        <div class="col-1">
                            <a href="" class="">
                                <i class="icon-cog icon-settings"></i>
                            </a>
                        </div>
                        <div class="col-1">
                            <a href="" class="">
                                <i class="icon-trash-empty icon-settings"></i>
                            </a>
                        </div>
                    </div>
                </div>
                {% endif %}
                
            </div>
        {% endfor %}
    
    {% endif %}

    <!-- Add competition -->
    {% if perms.competitions.add_competition %}
    <div class="row comp-list mt-2">
        <a href="" class="">
            <i class="icon-plus"></i>
        </a>
    </div>
    {% endif %}
</div>

{% endblock %}

ArcheryComp/competitions/templates/competitions/index.html
{% extends 'ArcheryComp/base.html' %}

{% block title %}
ArcheryComp Соревнования
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Соревнования</h1>  
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<div class="container">

    <div class="row">
        <div class="col-12">
            <h3>Виды соревнований</h3>
        </div>
        <div class="row comp-types">
            <div class="col text-center comp-type p-1 m-1">
                    <a href="{% url 'competitions:classical_list' %}">Классический лук</a>
            </div>
            <div class="col text-center comp-type p-1 m-1">
                    <a href="{% url 'competitions:compound_list' %}">Блочный лук</a>
            </div>
            <div class="col text-center comp-type p-1 m-1">
                    <a href="{% url 'competitions:D_list' %}">3Д стрельба из лука</a>
            </div>
            <div class="col text-center comp-type p-1 m-1">
                    <a href="{% url 'competitions:acheri_list' %}">Ачери</a>
            </div>
            <div class="col text-center comp-type p-1 m-1">
                    <a href="{% url 'competitions:asymmetrical_list' %}">Ассиметричный лук</a>
            </div>
        </div>
    </div>
</div>


<div class="container">
    

    
</div>
    
  
    
        
    </div>
</div>

{% endblock %}