ArcheryComp/ArcheryComp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.template.loader import render_to_string
from django.http import HttpResponse
from . import views

urlpatterns = [
    path('admin/',          admin.site.urls),
    path('',                views.IndexView.as_view(), name='home_page'),
    path('competitions/',   include('competitions.urls',   namespace='competitions')),
    path('participations/', include('participations.urls', namespace='participations')),
    path('users/',          include(('users.urls', 'users'), namespace='users')),
]

ArcheryComp/competitions/urls.py
from django.urls import path, include
from competitions import views
from participations import views as views_p

app_name = 'competitions'

urlpatterns = [
    path('',              views.IndexView.as_view(),            name='index'),
    path('classical/',    views.ClassicalListView.as_view(),    name='classical_list'),
    path('compound/',     views.CompoundListView.as_view(),     name='compound_list'),
    path('3D/',           views.DListView.as_view(),            name='D_list'),
    path('acheri/',       views.AcheriListView.as_view(),       name='acheri_list'),
    path('asymmetrical/', views.AsymmetricalListView.as_view(), name='asymmetrical_list'),
    path('competition_detail/<int:comp_id>/', include([
        path('', views.CompetitionDetailView.as_view(), name='competition_detail'),
        path('/<int:program_id>/', include([
            path('add_personal/', views_p.PersonalParticipationCreateView.as_view(), name='add_personal'),
            path('add_team/',     views_p.TeamParticipationCreateView.as_view(),     name='add_team'),
            path('add_mixed/',    views_p.MixedParticipationCreateView.as_view(),    name='add_mixed'),
            ])),
        path('/<int:participation_id>/', include([
            path('update_personal/', views_p.PersonalParticipationUpdateView.as_view(), name='update_personal'),
            path('update_team/',     views_p.TeamParticipationUpdateView.as_view(),     name='update_team'),
            path('update_mixed/',    views_p.MixedParticipationUpdateView.as_view(),    name='update_mixed'),
        ])),
        path('add_program/', views.IndexView.as_view(), name='add_program'),
        path('delete/', views.ClassicalDeleteView.as_view(), name='delete_classical_comp')
    ])),
]

ArcheryComp/participations/urls.py
from django.urls import path, include
from participations import views

app_name = 'participations'

urlpatterns = [
    path('', views.SportsmanListView.as_view(), name='sportsmans_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<str:username>/', include([
        path('participations_list/', views.PersonalParticipationListView.as_view(), name='participations_list'),
        path('team_participations_list/', views.TeamParticipationListView.as_view(), name='team_participations_list'),
        path('mixed_participations_list/', views.MixedParticipationListView.as_view(), name='mixed_participations_list'),
    ])),
    path('<str:username>', views.UserParticipitionsView.as_view(), name='user_part')
]

ArcheryComp/users/urls.py
from django.urls import path, include
from . import views
from . import forms

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/',  views.ProfileUpdateView.as_view(), name='profile'),
    path('profile/<str:username>/',  views.ProfileDetailView.as_view(), name='profile_view'),
    path('profile/<int:sportsmen_id>/',  views.ProfileDetailView.as_view(), name='profile_view_by_id'),
    path('login/',    views.MyLoginView.as_view(),  name='login'),
    path('', include('django.contrib.auth.urls')),
]

ArcheryComp/ArcheryComp/views.py
from django.shortcuts import render
from django.views import View

class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'ArcheryComp/index.html')

ArcheryComp/templates/ArcheryComp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'img/favicon.svg' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontello.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <!-- Общий заголовок для всех страниц --> 
        <div class="container-fluid ">
            <!-- Naviagtion panel -->    
            <nav>
                <!-- Навигационное меню -->
                <div class="container-fluid" > 
                    <div class="row">
            
                        <nav class="navbar navbar-expand-lg main-nav">
                            <div class="container-fluid">
                                <!-- Main icon -->
                                <a href="{% url 'home_page' %}" class="ArcheryComp">
                                    <i class="icon-bow-arrow"></i> ArcheryComp
                                </a>
                                <div class="nav-btn-container"> 
                                    <button class="navbar-toggler main-btn btn-transform nav-collapse-btn" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                        <i class="icon-arrow1 nav-i" ></i>
                                    </button>
                                </div>
                              
                                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                
                                <!-- Navigation buttons -->
                                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                  
                                    <li class="nav-item">
                                    <a href="{% url 'competitions:index' %}" class="main-btn nav-btn">
                                        <i class="icon-arrow-aim nav-i icon-arrow-aim-nav"></i> Соревнования
                                    </a>
                                    </li>
            
                                    <li class="nav-item">
                                        <a href="{% url 'participations:sportsmans_list' %}" class="main-btn nav-btn">
                                            <i class="icon-man-bow2 nav-i"></i>Спортсмены
                                        </a>
                                    </li>
            
                                </ul>
                                <!-- end Navigation buttons -->
                                <div class="line mb-1"></div>
                                <!-- auth -->
                                
                                <div class="row justify-content-center">
                                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                        {% if user.is_authenticated %}
                                            <li class="nav-item">
                                                <a href="{% url 'users:profile_view' user.username %}" class="main-btn nav-auth-btn">Профиль {{ user.username }}</a>
                                            </li>
            
                                            <li class="nav-item">
                                                <form action="{% url 'users:logout' %}" method="post">
                                                    {% csrf_token %}
                                                    <button type="submit" class="main-btn nav-auth-btn btn-w-100">Выйти</button>
                                                </form>
                                            </li>
                                        {% else %}
                                            <li class="nav-item ">
                                                <a href="{% url 'users:login' %}" class="main-btn nav-auth-btn">Вход</a>
                                            </li>
            
                                            <li class="nav-item ">
                                                <a href="{% url 'users:register' %}" class="main-btn nav-auth-btn">Регистрация</a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </div>
                
                                <!-- end auth -->

                              </div>
                            </div>
                          </nav>
                        
                        
                        
                        
                    </div>
                </div>
                
            
            </nav>
            
            
                
            <div class="line"></div>
        </div>
        
        
    </header>
    <div class="sub-header">
        {% block header %}
        {% endblock %}
    </div>

    <main>
        
        {% block content %}
        <!-- Основное содержимое страницы -->
        {% endblock %}
    </main>
    
    
    <footer>
        <!-- Общий футер для всех страниц -->
    </footer>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>