ArcheryComp/ArcheryComp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.template.loader import render_to_string
from django.http import HttpResponse
from . import views

urlpatterns = [
    path('admin/',          admin.site.urls),
    path('',                views.IndexView.as_view(), name='home_page'),
    path('competitions/',   include('competitions.urls',   namespace='competitions')),
    path('participations/', include('participations.urls', namespace='participations')),
    path('users/',          include(('users.urls', 'users'), namespace='users')),
]

ArcheryComp/competitions/urls.py
from django.urls import path, include
from competitions import views
from participations import views as views_p

app_name = 'competitions'

urlpatterns = [
    path('',              views.IndexView.as_view(),            name='index'),
    path('classical/',    views.ClassicalListView.as_view(),    name='classical_list'),
    path('compound/',     views.CompoundListView.as_view(),     name='compound_list'),
    path('3D/',           views.DListView.as_view(),            name='D_list'),
    path('acheri/',       views.AcheriListView.as_view(),       name='acheri_list'),
    path('asymmetrical/', views.AsymmetricalListView.as_view(), name='asymmetrical_list'),
    path('competition_detail/<int:comp_id>/', include([
        path('', views.CompetitionDetailView.as_view(), name='competition_detail'),
        path('/<int:program_id>/', include([
            path('add_personal/', views_p.PersonalParticipationCreateView.as_view(), name='add_personal'),
            path('add_team/',     views_p.TeamParticipationCreateView.as_view(),     name='add_team'),
            path('add_mixed/',    views_p.MixedParticipationCreateView.as_view(),    name='add_mixed'),
            ])),
        path('/<int:participation_id>/', include([
            path('update_personal/', views_p.PersonalParticipationUpdateView.as_view(), name='update_personal'),
            path('update_team/',     views_p.TeamParticipationUpdateView.as_view(),     name='update_team'),
            path('update_mixed/',    views_p.MixedParticipationUpdateView.as_view(),    name='update_mixed'),
        ])),
        path('add_program/', views.IndexView.as_view(), name='add_program'),
        path('delete/', views.ClassicalDeleteView.as_view(), name='delete_classical_comp')
    ])),
]

ArcheryComp/participations/urls.py
from django.urls import path, include
from participations import views

app_name = 'participations'

urlpatterns = [
    path('', views.SportsmanListView.as_view(), name='sportsmans_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<str:username>/', include([
        path('participations_list/', views.PersonalParticipationListView.as_view(), name='participations_list'),
        path('team_participations_list/', views.TeamParticipationListView.as_view(), name='team_participations_list'),
        path('mixed_participations_list/', views.MixedParticipationListView.as_view(), name='mixed_participations_list'),
    ])),
    path('<str:username>', views.UserParticipitionsView.as_view(), name='user_part')
]

ArcheryComp/users/urls.py
from django.urls import path, include
from . import views
from . import forms

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/',  views.ProfileUpdateView.as_view(), name='profile'),
    path('profile/<str:username>/',  views.ProfileDetailView.as_view(), name='profile_view'),
    path('profile/<int:sportsmen_id>/',  views.ProfileDetailView.as_view(), name='profile_view_by_id'),
    path('login/',    views.MyLoginView.as_view(),  name='login'),
    path('', include('django.contrib.auth.urls')),
]

ArcheryComp/participations/forms.py
from typing import Any, Mapping
from django.core.files.base import File
from django.db.models.base import Model
from django.forms import ModelForm
from django.forms.utils import ErrorList
from .models import PersonalParticipation, TeamParticipation, MixedParticipation
from django import forms

class PersonalParticipationForm(ModelForm):
    class Meta:
        model = PersonalParticipation
        fields = ['sportsman',
                  'place', 'place_qualification', 'sum_qualification']
        
        labels = {'sportsman':'Спортсмен', 
                  'place':'Место',
                  'place_qualification':'Место в квалификации',
                  'sum_qualification':'Сумма в квалификации'}
        
class TeamParticipationForm(ModelForm):
    class Meta:
        model = TeamParticipation
        fields = ['sportsman_1', 'sportsman_2', 'sportsman_3',
                  'place', 'place_qualification', 'sum_qualification']
        
        labels = {'sportsman_1':'Спортсмен 1',
                  'sportsman_2':'Спортсмен 2',
                  'sportsman_3':'Спортсмен 3', 
                  'place':'Место',
                  'place_qualification':'Место в квалификации',
                  'sum_qualification':'Сумма в квалификации'}

class MixedParticipationForm(ModelForm):
    class Meta:
        model = MixedParticipation
        fields = ['sportsman_M', 'sportsman_F',
                  'place', 'place_qualification', 'sum_qualification']
        
        labels = {'sportsman_M':'Спортсмен М',
                  'sportsman_F':'Спортсмен Ж', 
                  'place':'Место',
                  'place_qualification':'Место в квалификации',
                  'sum_qualification':'Сумма в квалификации'}


class PersonalProgramForm(ModelForm):
    class Meta:
        model = PersonalParticipation
        fields = ['program',
                  'sportsman',
                  'place', 'place_qualification', 'sum_qualification']

        labels = {'sportsman': 'Спортсмен',
                  'place': 'Место',
                  'place_qualification': 'Место в квалификации',
                  'sum_qualification': 'Сумма в квалификации'}

class TeamProgramForm(ModelForm):
    class Meta:
        model = TeamParticipation
        fields = ['program',
                  'sportsman_1', 'sportsman_2', 'sportsman_3',
                  'place', 'place_qualification', 'sum_qualification']

        labels = {'sportsman': 'Спортсмен',
                  'place': 'Место',
                  'place_qualification': 'Место в квалификации',
                  'sum_qualification': 'Сумма в квалификации'}

class MixedProgramForm(ModelForm):
    class Meta:
        model = MixedParticipation
        fields = ['program',
                  'sportsman_M', 'sportsman_F',
                  'place', 'place_qualification', 'sum_qualification']

        labels = {'sportsman': 'Спортсмен',
                  'place': 'Место',
                  'place_qualification': 'Место в квалификации',
                  'sum_qualification': 'Сумма в квалификации'}

ArcheryComp/participations/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.urls import reverse
from .models import PersonalParticipation, TeamParticipation, MixedParticipation
from django.contrib.auth.models import User
from users.models import Profile
from django.db.models import Q
from django.views.generic import ListView
from .forms import PersonalParticipationForm, TeamParticipationForm, MixedParticipationForm
from competitions.models import Competition, Program

class SportsmanListView(ListView):
    model = User
    template_name = 'participations/sportsman_list.html'
 

    def get(self,  request, *args, **kwargs):
        sportsmans = self.get_queryset().order_by('last_name')
        return render(request, self.template_name, context={'sportsmans': sportsmans}) 

class PersonalParticipationListView(ListView):
    model = PersonalParticipation
    template_name = 'participations/user_participation.html'
    def get(self, request, *args, **kwargs):
        
        participations = PersonalParticipation.objects.filter(sportsman__username=self.kwargs['username'])
        competitions = {}
        for participation in participations:
            if not competitions.get(participation.competition):
                competitions.update({participation.competition:[]})
            competitions.get(participation.competition).append(participation)
        
        return render(request, self.template_name, context={'competitions': competitions})


class TeamParticipationListView(ListView):
    model = TeamParticipation

    def get(self, request, *args, **kwargs):
        competition_prev = 0
        participations = TeamParticipation.objects.filter(Q(sportsman_1__username=self.kwargs['username'])
                                                          | Q(sportsman_2__username=self.kwargs['username'])
                                                          | Q(sportsman_3__username=self.kwargs['username']))
        participations_html = '<h2>Список командных участий</h2><ul>'
        for participation in participations:
            competition = participation.competition
            competition_url = reverse('competitions:competition_detail',
                                      kwargs={'comp_id': competition.comp_id})
            team = [participation.sportsman_1, participation.sportsman_2, participation.sportsman_3]
            team.remove(get_object_or_404(User, username=self.kwargs['username']))
            if competition != competition_prev:
                participations_html += f'<a href="{competition_url}">{participation.competition.title}</a></br>'
            participations_html += (f'<li>    {participation.program.name} {participation.place} '
                                    f'{participation.place_qualification} {participation.sum_qualification}</br>'
                                    f'в команде с ')
            for i in range(2):
                teammate_url = reverse('users:profile_view', kwargs={'username': team[i].username})
                participations_html += f'<a href="{teammate_url}">{team[i].last_name} {team[i].first_name} </a>'
            participations_html += '</li>'
            competition_prev = competition
        participations_html += '</ul>'
        return HttpResponse(participations_html)

# class TeamParticipationListView(ListView):
#     model = TeamParticipation
#     template_name = 'participations/user_teamparticipation.html'

    
    

    # def get(self, request, *args, **kwargs):
    #     competition_prev = 0
    #     participations = TeamParticipation.objects.filter(Q(sportsman_1__username=self.kwargs['username'])
    #                                                       | Q(sportsman_2__username=self.kwargs['username'])
    #                                                       | Q(sportsman_3__username=self.kwargs['username']))
    #     competitions = {}

    #     for participation in participations:
    #         if not competitions.get(participation.competition):
    #             competitions.update({participation.competition:[]})
            
    #         team = [participation.sportsman_2, participation.sportsman_3]
    #         team.remove(get_object_or_404(User, username=self.kwargs['username']))
    #         competitions.get(participation.competition).append([participation,
    #                                                            team])
            
    #         competition = participation.competition
    #         competition_url = reverse('competitions:competition_detail',
    #                                   kwargs={'comp_id': competition.comp_id})
            
            
    #         if competition != competition_prev:
    #             participations_html += f'<a href="{competition_url}">{participation.competition.title}</a></br>'
    #         participations_html += (f'<li>    {participation.program.name} {participation.place} '
    #                                 f'{participation.place_qualification} {participation.sum_qualification}</br>'
    #                                 f'в команде с ')
    #         for i in range(2):
    #             teammate_url = reverse('users:profile_view', kwargs={'username': team[i].username})
    #             participations_html += f'<a href="{teammate_url}">{team[i].last_name} {team[i].first_name} </a>'
    #         participations_html += '</li>'
    #         competition_prev = competition
    #     participations_html += '</ul>'
        
    #     competitions = [[key]+value for key, value in competitions.items()]
        
    #     return render(request, self.template_name, context={'competitions': competitions})


class MixedParticipationListView(ListView):
    model = MixedParticipation

    def get(self, request, *args, **kwargs):
        competition_prev = 0
        sportsman = User.objects.get(username=self.kwargs['username'])
        if sportsman.profile.sex == 'M':
            participations = MixedParticipation.objects.filter(sportsman_M__username = self.kwargs['username'])
        else:
            participations = MixedParticipation.objects.filter(sportsman_F__username = self.kwargs['username'])
        participations_html = '<h2>Список смешанных командных участий</h2><ul>'
        for participation in participations:
            competition = participation.competition
            competition_url = reverse('competitions:competition_detail',
                                      kwargs={'comp_id': competition.comp_id})
            if competition != competition_prev:
                participations_html += f'<a href="{competition_url}">{participation.competition.title}</a></br>'
            participations_html += (f'<li>    {participation.program.name} {participation.place} '
                                    f'{participation.place_qualification} {participation.sum_qualification}</br>'
                                    f'в команде с ')
            if sportsman.profile.sex == 'M':
                teammate = participation.sportsman_F
            else:
                teammate = participation.sportsman_M
            teammate_url = reverse('users:profile_view', kwargs={'username': teammate.username})
            participations_html += f'<a href="{teammate_url}">{teammate.last_name} {teammate.first_name} </a>'
            participations_html += '</li>'
            competition_prev = competition
        participations_html += '</ul>'
        return HttpResponse(participations_html)

def profile(request, username):
    template_name = 'participations/user_partisipations.html'
    return render(request, template_name, context={'username': username})

class ParticipationCreateView(CreateView):
    template_name = 'participations/add_participation.html'

    def form_valid(self, form):
        form.instance.competition = get_object_or_404(Competition, pk=self.kwargs['comp_id'])
        form.instance.program =     get_object_or_404(Program,     pk=self.kwargs['program_id'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('competitions:competition_detail', kwargs={'comp_id': self.kwargs['comp_id']})

class PersonalParticipationCreateView(PermissionRequiredMixin, ParticipationCreateView):
    model = PersonalParticipation
    form_class = PersonalParticipationForm
    permission_required = 'participations.add_personalparticipation'


class TeamParticipationCreateView(PermissionRequiredMixin, ParticipationCreateView):
    model = TeamParticipation
    form_class = TeamParticipationForm
    permission_required = 'participations.add_teamparticipation'

class MixedParticipationCreateView(PermissionRequiredMixin, ParticipationCreateView):
    model = MixedParticipation
    form_class = MixedParticipationForm
    permission_required = 'participations.add_mixedparticipation'

from .forms import PersonalProgramForm, TeamProgramForm, MixedProgramForm

class ProgramCreateView(CreateView):
    template_name = 'participations/add_participation.html'

    def form_valid(self, form):
        form.instance.competition = get_object_or_404(Competition, pk=self.kwargs['comp_id'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('competitions:competition_detail', kwargs={'comp_id': self.kwargs['comp_id']})

class PersonalProgramCreateView(ProgramCreateView):
    model = PersonalParticipation
    form_class = PersonalProgramForm
    permission_required = 'participations.add_personalparticipation'

class TeamProgramCreateView(ProgramCreateView):
    model = TeamParticipation
    form_class = TeamProgramForm
    permission_required = 'participations.add_teamparticipation'

ArcheryComp/participations/templates/participations/add_participation copy.html
{% extends 'ArcheryComp/base.html' %}

{% block title %}
ArcheryComp Добавление участия
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1> {{ object.__str__ }} - {{ object.title }}</h1>
        </div>
    </div>
</div>
{% endblock %}


{% block content %}
<div class="container">
    <div class="row mt-2">
        <h3>Добавить участие в соревнование {{ form.temp }} 1</h3>
    </div>

    <div class="row">
        <form method="post">
            {% csrf_token %}

            {% for field in form %}
                <div class="row justify-content-start mx-1 mt-2">
                    <div class="col-xl-4 col-md-7 col-sm-12">
                        <div class="row">{{field.label}}</div>
                        <div class="row">{{field}}</div>
                    </div>
                </div>
            {% endfor %}

            
            <div class="row justify-content-start mx-1 mt-4">
                <div class="col-xl-4 col-md-7 col-sm-12">
                    <div class="row">
                        <div class="col-6">
                            <button type="submit" class="confirm-btn btn-w-100">Добавить участие</button>
                        </div>
                        <div class="col-6">
                            <a href="#" class="confirm-btn">Отменить</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
    

{% endblock %}

ArcheryComp/participations/templates/participations/add_participation.html
{% extends 'ArcheryComp/base.html' %}

{% block title %}
ArcheryComp Изменение участия
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1> {{object.competition.discipline}} - {{ object.competition.title }}</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-2">
        <h3>Изменение участие</h3>
    </div>
    <div class="row">
        <form method="post">
            <div class="row">
                {% csrf_token %}
                
                {% for field in form %}
                <div class="row justify-content-start mx-1 mt-2">
                    <div class="col-xl-4 col-md-7 col-sm-12">
                        <div class="row">{{field.label}}</div>
                        <div class="row">{{field}}</div>
                    </div>
                </div>
                {% endfor %}

                <div class="row justify-content-start mx-1 mt-4">
                    <div class="col-xl-4 col-md-7 col-sm-12">
                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="confirm-btn" style="width: 100%;">Сохранить</button>
                            </div>
                            <div class="col-6">
                                <a href="javascript:history.back()" class="confirm-btn">Отменить</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            
        </form>
    </div>
    
</div>


{% endblock %}

ArcheryComp/participations/templates/participations/delete_participation.html
{% extends 'ArcheryComp/base.html' %}

{% block title %}
ArcheryComp Удаление участия
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        Вы уверены, что хотите удалить это участие?
    </div>
    <div class="row">
        <form action="{% url 'competitions:competition_detail' participation.competition.comp_id %}">
            {% csrf_token %}
            <input type="submit" value="Удалить">
            <a href="{% url 'competitions:competition_detail' participation.competition.comp_id %}">Отмена</a>
        </form>
    </div>
</div>

{% endblock %}

ArcheryComp/participations/templates/participations/index.html
{% extends 'ArcheryComp/base.html' %}

{% block title %}
ArcheryComp Спортсмены
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Спортсмены</h1>  
        </div>
    </div>
</div>
{% endblock %}


{% block content %}
<div class="container">
    
    <div class="row">
        <div class="col-12">
            Что-то еще...
        </div>
    </div>
</div>
{% endblock %}

ArcheryComp/participations/templates/participations/sportsman_list.html
{% extends 'ArcheryComp/base.html' %}

{% block title %}
ArcheryComp Список спортсменов
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Список спортсменов</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    
    <div class="row">

        {% for sportsman in sportsmans %}
        <a href="{% url 'users:profile_view' sportsman.username %}"  >    
            <div class="container-fluid " >
                <div class="row mt-2">
                    <div class="col-3 sportman-el">
                        <div class="row">
                            <div class="col">
                                {{ sportsman.last_name }}
                            </div>
                            <div class="col">
                                {{ sportsman.first_name }}
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </a>
            <div class="line mt-1"></div>
        {% endfor %}

    </div>
    
</div>


{% endblock %}

ArcheryComp/participations/templates/participations/update_participation.html
{% extends 'ArcheryComp/base.html' %}

{% block title %}
ArcheryComp Изменение участия
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1> {{object.competition.discipline}} - {{ object.competition.title }}</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-2">
        <h3>Изменение участие</h3>
    </div>
    <div class="row">
        <form method="post">
            <div class="row">
                {% csrf_token %}
                
                {% for field in form %}
                <div class="row justify-content-start mx-1 mt-2">
                    <div class="col-xl-4 col-md-7 col-sm-12">
                        <div class="row">{{field.label}}</div>
                        <div class="row">{{field}}</div>
                    </div>
                </div>
                {% endfor %}

                <div class="row justify-content-start mx-1 mt-4">
                    <div class="col-xl-4 col-md-7 col-sm-12">
                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="confirm-btn btn-w-100">Сохранить</button>
                            </div>
                            <div class="col-6">
                                <a href="javascript:history.back()" class="confirm-btn">Отменить</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            
        </form>
    </div>
    
</div>


{% endblock %}

ArcheryComp/participations/templates/participations/user_part.html
{% extends 'ArcheryComp/base.html' %} 

{% block title %}
ArcheryComp Part
{% endblock %}

{% block content %}
<!--username - id спорстмена ... -->
<p>Участия спорстмена с id  {{ username }}</p>

{% endblock content %}

ArcheryComp/participations/templates/participations/user_participation.html
{% extends 'ArcheryComp/base.html' %}

{% block title %}
ArcheryComp Список спортсменов
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Список участий {{user_.username}}</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container mt-2">
    
    <div class="row">
        <h3>Индивидуальные участия</h3>
    </div>
    
    <div class="row">
        <div class="line-k mb-2"></div>
        {% for competition,participations in competitions.items %}
            <div class="row">
                <div class="row">
                    <h4>{{competition.title}}</h4>
                </div>
                <div class="row">
                    <div class="col-6">Программа</div>
                    <div class="col-2">Место</div>
                    <div class="col-2">Место в квалификации</div>
                    <div class="col-2">Сумма в квалификации</div>
                </div>
                <div class="line mb-2"></div>
                {% for participation in participations %}
                <div class="row">
                    <div class="col-6">
                        {{participation.program.name}}
                    </div>
                    <div class="col-2">
                        {{participation.place}}
                    </div>
                    <div class="col-2">
                        {{participation.place_qualification}}
                    </div>
                    <div class="col-2">
                        {{participation.sum_qualification}}
                    </div>
                </div>
                
                {% endfor %}
            </div>        
            <div class="line-k my-2"></div>
        {% endfor %}

    </div>
    
</div>


{% endblock %}

ArcheryComp/participations/templates/participations/user_partisipations.html
{% extends 'ArcheryComp/base.html' %}

{% block title %}
ArcheryComp Участия
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Участия спортсмена {{username}}</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container mt-2">
    
    <div class="row user-part-refs">
        <a href="{% url 'participations:participations_list' username %}" class="sportman-el">Список личных участий</a>
    </div>
    <div class="row user-part-refs">
        <a href="{% url 'participations:team_participations_list' username %}" class="sportman-el">Список командных участий</a>
    </div>
    <div class="row user-part-refs">
        <a href="{% url 'participations:mixed_participations_list' username %}" class="sportman-el">Список смешанных участий</a>
    </div>
    
</div>


{% endblock %}

ArcheryComp/participations/templates/participations/user_teamparticipation.html
{% extends 'ArcheryComp/base.html' %}

{% block title %}
ArcheryComp Список спортсменов
{% endblock %}

{% block header %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Список участий {{user_.username}}</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container mt-2">
    
    <div class="row">
        <h3>Командные участия</h3>
    </div>
    
    <div class="row">
        <div class="line-k mb-2"></div>
        {% for competition,team_data in competitions.items %}
            <div class="row">
                <div class="row">
                    <h4>{{competition.title}}</h4>
                </div>
                <div class="row">
                    <div class="col-6">Программа</div>
                    <div class="col-6">Команда</div>
                    <div class="col-2">Место</div>
                    <div class="col-2">Место в квалификации</div>
                    <div class="col-2">Сумма в квалификации</div>
                </div>
                <div class="line mb-2"></div>
                {% for participation in participations %}
                <div class="row">
                    <div class="col-6">
                        {{participation.program.name}}
                    </div>
                    <div class="col-2">
                        {{participation.place}}
                    </div>
                    <div class="col-2">
                        {{participation.place_qualification}}
                    </div>
                    <div class="col-2">
                        {{participation.sum_qualification}}
                    </div>
                </div>
                
                {% endfor %}
            </div>        
            <div class="line-k my-2"></div>
        {% endfor %}

    </div>
    
</div>


{% endblock %}